### ISSUE TITLE
[Feature] Don't crash when items cannot be found

### ISSUE THREAD

**Issue by asdfugil** [MeemeeLab/node-anime-viewer#11]
I would not say this is a bug, but just terrible UX.

Currently, this crashes if:

- Searching for a nonexistent anime (e.g. `sjdgsajfsgj`)
- Play the next episode, but the current episode is the last one.
- Play the previous episode, but the current episode is the first one

Instead of crashing, it is better to display an error message as the crash message does not point to the actual problem with the user input.

**Comment by MeemeeLab** [comment]
Fixed in 2307e97
