### ISSUE TITLE
[Bug] Doesnt show all episodes

### ISSUE THREAD

**Issue by Quicksilver151** [MeemeeLab/node-anime-viewer#21]
searching for anime with over 1000 eps like one piece only shows episodes over 1000 for selection

**Comment by Quicksilver151** [comment]
ok so just tested some more and seems like its the same case for any anime with over 100 episodes
it only lists the episodes closest to the highest hundred

**Comment by MeemeeLab** [comment]
Can you tell me the name of the anime?

**Comment by Quicksilver151** [comment]
any anime with over 100 episodes
like one piece, naruto etc...
btw
selecting naruto shippuden for some reason crashed the program
this is the error i get
`
node-anime-viewer 1.0.3
Copyright (C) 2021 [object Object]

Select episode: 
(node:1005698) UnhandledPromiseRejectionWarning: TypeError: [terminal] gridMenu(): argument #0 should be a non-empty array
    at Terminal.gridMenu (/usr/local/lib/node_modules/node-anime-viewer/node_modules/terminal-kit/lib/gridMenu.js:83:70)
    at SelectEpisodeInterface.Init (file:///usr/local/lib/node_modules/node-anime-viewer/src/modules/interface.js:51:19)
    at new Interface (file:///usr/local/lib/node_modules/node-anime-viewer/src/modules/interface.js:19:14)
    at new SelectEpisodeInterface (file:///usr/local/lib/node_modules/node-anime-viewer/src/modules/interface.js:48:8)
    at Object.selectAnime (file:///usr/local/lib/node_modules/node-anime-viewer/src/index.js:50:48)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1005698) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1005698) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by MeemeeLab** [comment]
That error seems happens with episode have over 100 episodes too.
gogoanime shows html like this:
![image](https://user-images.githubusercontent.com/57629983/147652806-b229aa1f-b4b9-4cce-b34f-87091d1f6d8a.png)

Merging new issue to this.

**Comment by MeemeeLab** [comment]
Fixed in 72a1ec7

**Comment by Quicksilver151** [comment]
im still not seeing all available episodes tho
