### ISSUE TITLE
[Request] Problems with history file

### ISSUE THREAD

**Issue by asdfugil** [MeemeeLab/node-anime-viewer#25]
The history is located at the root of the source tree, which may not be writable (e.g. /usr/local/lib/node_modules/node-anime-viewer) on a linux system with system node.js

Different users on the same system will have the same history

A good place for the history file is:

```
import os from 'os'
os.homedir() + '/.node_anime_viewer_data.json`
```

(Just in case it will hold more than history in the future)

**Comment by MeemeeLab** [comment]
Implemented in 697f4f9
