### ISSUE TITLE
[Issue] Showing duplicate qualities

### ISSUE THREAD

**Issue by somerandomcloud** [MeemeeLab/node-anime-viewer#33]
Was setting out to watch Classroom of the elite, but when I got to the resolution part, it gave me duplicate options, and only one of the two worked. I cant exactly tell what could be causing this, but it doesnt seem to happen for other anime.

**Comment by RazerMoon** [comment]
![image](https://user-images.githubusercontent.com/33849459/147908282-71327c92-2ce7-4a15-ba39-bcd6c1c4366a.png)

Can confirm this does happen. In my case it is a different anime.

**Comment by MeemeeLab** [comment]
@somerandomcloud @RazerMoon Can you tell me what anime it's happening?

**Comment by somerandomcloud** [comment]
For me it is happening on Classroom of the elite

**Comment by MeemeeLab** [comment]
New commit should fix this problem, If you still having this problem please reopen.
