### ISSUE TITLE
[Bug] Proxy 403 Forbidden Error

### ISSUE THREAD

**Issue by JacobTempleton** [MeemeeLab/node-anime-viewer#41]
Browser: Brave
OS: OSX Monterey 12.1
Apache2 version 2.4.51
Node.js v17.3.1

Whenever trying to play a video using the VLC player some random localhost port is opened and a 403 "access to localhost was denied error" is thrown. Downloading appears to work normally. I've tried messing around with apache config files, browser settings, and the config of node-anime-viewer but the forbidden error has stayed the same. I've tested running other localhost sites and they work normally with no 403 errors. I've also tried switching to MPV player, but it doesn't seem to launch anything using node-anime-viewer. Other tools like ani-cli and youtube-dl work normally including while using MPV.

<img width="136" alt="Screen Shot 2022-01-13 at 11 42 19 AM" src="https://user-images.githubusercontent.com/94549669/149272638-8f356e9c-465f-4668-a2f3-6990c388e096.png">
<img width="641" alt="Screen Shot 2022-01-13 at 11 42 09 AM" src="https://user-images.githubusercontent.com/94549669/149272635-ebc84189-7814-4f0d-8e53-598a7613f04a.png">

I'm not sure the problem is caused by node-anime-viewer itself, but nothing else has caused this error, and after trying some fixes for similar localhost 403 errors the problem has persisted for node-anime-viewer specifically.

**Comment by MeemeeLab** [comment]
Can you tell me the title of anime that happening?

**Comment by JacobTempleton** [comment]
> Can you tell me the title of anime that happening?

The error pops up for all animes and episodes as far as I can tell. Specifically, I've tried: Clannad, Naruto, One Piece, and Cowboy Bebop.

**Comment by MeemeeLab** [comment]
Looks like they updated the cloudflare filter.
