### ISSUE TITLE
VLC cant play media

### ISSUE THREAD

**Issue by emm312** [MeemeeLab/node-anime-viewer#48]
### Version

1.2.6

### Platform

Microsoft Windows NT 10.0.22000.0 x64

### What steps will reproduce the bug?

I was trying to play something from history.

### How often does it reproduce? Is there a required condition?

Every time.

### What is the expected behavior?

Anime plays.

### What do you see instead?

Your input can't be opened:
VLC is unable to open the MRL 'http://localhost:52216'. Check the log for details.

**Comment by emm312** [comment]
I also cant download anything

**Comment by MeemeeLab** [comment]
Moving to #49.
